export const CHANGE_CART = 'CHANGE_CART';
export const CHANGE_CART_REQUEST = 'CHANGE_CART_REQUEST';
export const CHANGE_CART_SUCCESS = 'CHANGE_CART_SUCCESS';
export const CHANGE_CART_FAILURE = 'CHANGE_CART_FAILURE';

export const GET_CART = 'GET_CART';
export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';

