export const GET_LEFT_CATEGORY = 'GET_LEFT_CATEGORY';
export const GET_LEFT_CATEGORY_SUCCESS = 'GET_LEFT_CATEGORY_SUCCESS';
export const GET_LEFT_CATEGORY_FAILURE = 'GET_LEFT_CATEGORY_FAILURE';
export const GET_LEFT_CATEGORY_REQUEST = 'GET_LEFT_CATEGORY_REQUEST';

export const GET_RIGHT_FILTER = 'GET_RIGHT_FILTER';
export const GET_RIGHT_FILTER_SUCCESS = 'GET_RIGHT_FILTER_SUCCESS';
export const GET_RIGHT_FILTER_FAILURE = 'GET_RIGHT_FILTER_FAILURE';
export const GET_RIGHT_FILTER_REQUEST = 'GET_RIGHT_FILTER_REQUEST';

export const GET_RIGHT_ITEM = 'GET_RIGHT_ITEM';
export const GET_RIGHT_ITEM_SUCCESS = 'GET_RIGHT_ITEM_SUCCESS';
export const GET_RIGHT_ITEM_FAILURE = 'GET_RIGHT_ITEM_FAILURE';
export const GET_RIGHT_ITEM_REQUEST = 'GET_RIGHT_ITEM_REQUEST';

export const TOGGLE_EXPAND= 'TOGGLE_EXPAND';
